# Generated by Django 3.1.7 on 2021-03-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=20)),
                ('Email', models.EmailField(max_length=254)),
                ('Age', models.IntegerField()),
                ('Password', models.CharField(max_length=8)),
            ],
        ),
    ]
