# Generated by Django 3.1.7 on 2021-04-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='registration',
            name='ConfirmPassword',
            field=models.CharField(default=12345678, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='registration',
            name='Photo',
            field=models.ImageField(default=2, upload_to='media/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='registration',
            name='Email',
            field=models.EmailField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Lastname',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='registration',
            name='Password',
            field=models.CharField(max_length=20),
        ),
    ]
