# Generated by Django 3.1.7 on 2021-05-18 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_registration_confirmpassword'),
    ]

    operations = [
        migrations.CreateModel(
            name='Registratione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Firstname', models.CharField(max_length=20)),
                ('Lastname', models.CharField(max_length=30)),
                ('Email', models.EmailField(max_length=50)),
                ('Age', models.IntegerField()),
                ('Photo', models.ImageField(upload_to='media/')),
                ('Password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
