# Generated by Django 3.1.7 on 2021-05-18 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210518_1959'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registratione',
            old_name='Lastname',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='registratione',
            old_name='Firstname',
            new_name='Picturename',
        ),
        migrations.RenameField(
            model_name='registratione',
            old_name='Age',
            new_name='Price',
        ),
        migrations.RemoveField(
            model_name='registratione',
            name='Email',
        ),
        migrations.RemoveField(
            model_name='registratione',
            name='Password',
        ),
    ]
